import { IAttendanceRequest } from "@/src/interfaces";

export const attendanceRequestData: IAttendanceRequest[] = [
  {
    id: 1,
    employeeId: "EMP001",
    reason: "Medical Appointment",
    date: "2024-06-10",
    inTime: "09:00:00",
    outTime: "17:00:00",
    employeeName: "Alice Johnson",
    designation: "Software Engineer",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 2,
    employeeId: "EMP002",
    reason: "Family Emergency",
    date: "2024-06-11",
    inTime: "10:00:00",
    outTime: "18:00:00",
    employeeName: "Bob Smith",
    designation: "Product Manager",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 3,
    employeeId: "EMP003",
    reason: "Personal Leave",
    date: "2024-06-12",
    inTime: "08:30:00",
    outTime: "16:30:00",
    employeeName: "Clara Lee",
    designation: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    employeeId: "EMP004",
    reason: "Vacation",
    date: "2024-06-13",
    inTime: "09:15:00",
    outTime: "17:15:00",
    employeeName: "David Kim",
    designation: "QA Analyst",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    employeeId: "EMP005",
    reason: "Sick Leave",
    date: "2024-06-14",
    inTime: "10:00:00",
    outTime: "18:00:00",
    employeeName: "Eva Green",
    designation: "HR Specialist",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
];
