import { ILeaveRequest } from "@/src/interfaces";

export const leaveRequestData: ILeaveRequest[] = [
  {
    id: 1,
    employeeId: "EMP001",
    reason: "Medical Appointment",
    dateFrom: "2024-06-10",
    dateTo: "2024-06-14",
    employeeName: "Alice Johnson",
    designation: "Software Engineer",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    type: "Sick Leave",
    duration: "Full Day",
  },
  {
    id: 2,
    employeeId: "EMP002",
    reason: "Family Emergency",
    dateFrom: "2024-06-12",
    dateTo: "2024-06-12",
    employeeName: "Bob Smith",
    designation: "HR Manager",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    type: "Casual Leave",
    duration: "Half Day",
  },
  {
    id: 3,
    employeeId: "EMP003",
    reason: "Vacation",
    dateFrom: "2024-06-15",
    dateTo: "2024-06-19",
    employeeName: "Clara Lee",
    designation: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    type: "Annual Leave",
    duration: "Full Day",
  },
  {
    id: 4,
    employeeId: "EMP004",
    reason: "Conference Attendance",
    dateFrom: "2024-06-20",
    dateTo: "2024-06-22",
    employeeName: "David Kim",
    designation: "Project Manager",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    type: "Official Duty",
    duration: "Full Day",
  },
  {
    id: 5,
    employeeId: "EMP005",
    reason: "Child's School Event",
    dateFrom: "2024-06-18",
    dateTo: "2024-06-18",
    employeeName: "Eva Green",
    designation: "QA Analyst",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    type: "Casual Leave",
    duration: "Half Day",
  },
  {
    id: 6,
    employeeId: "EMP006",
    reason: "Personal Work",
    dateFrom: "2024-06-23",
    dateTo: "2024-06-24",
    employeeName: "Frank Miller",
    designation: "Backend Developer",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    type: "Casual Leave",
    duration: "Full Day",
  },
  {
    id: 7,
    employeeId: "EMP007",
    reason: "Marriage",
    dateFrom: "2024-06-25",
    dateTo: "2024-06-30",
    employeeName: "Grace Park",
    designation: "Frontend Developer",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    type: "Special Leave",
    duration: "Full Day",
  },
  {
    id: 8,
    employeeId: "EMP008",
    reason: "Maternity Checkup",
    dateFrom: "2024-06-15",
    dateTo: "2024-06-15",
    employeeName: "Helen Carter",
    designation: "Product Owner",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    type: "Sick Leave",
    duration: "Half Day",
  },
  {
    id: 9,
    employeeId: "EMP009",
    reason: "Bereavement",
    dateFrom: "2024-06-11",
    dateTo: "2024-06-13",
    employeeName: "Ian Wright",
    designation: "DevOps Engineer",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    type: "Compassionate Leave",
    duration: "Full Day",
  },
  {
    id: 10,
    employeeId: "EMP010",
    reason: "Exam Preparation",
    dateFrom: "2024-06-21",
    dateTo: "2024-06-22",
    employeeName: "Julia Adams",
    designation: "Intern",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    type: "Study Leave",
    duration: "Full Day",
  },
];
